#
# Create briges on NCs
#

- name: Creates the Bridge config file | VLAN
  template: src=bridge.j2 dest="{{ netcfg_path }}/ifcfg-{{ bridge_prefix }}{{ vlan_tag }}"
  tags:
  - network_config
  when:
  - use_vlans

- name: Creates the Bridge config file | NOVLAN
  template: src=bridge.j2 dest="{{ netcfg_path }}/ifcfg-{{ bridge_prefix }}{{ bridge_id }}"
  tags:
  - network_config
  when:
  - not use_vlans

- name: Update the bridged interface config file
  template: src=iface.j2 dest="{{ netcfg_path }}/ifcfg-{{ hostvars[inventory_hostname]['vnet_private'] }}"
  tags:
  - network_config
  when:
  - not use_vlans

- name: Network restart
  service: name=network state=restarted
  tags:
  - network_config

- name: Gather new informations
  setup:
  tags:
  - network_config
