#
# VLANs configuration
#

- name: Create the VLAN config file
  template: src=vlan.j2 dest="{{ netcfg_path }}/ifcfg-{{ vlan_iface }}.{{ vlan_tag }}"
  tags:
  - network_config

- name: Restart network
  service: name=network state=restarted
  tags:
  - network_config

- name: Gather new info
  setup:
  tags:
  - network_config
